version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_IMAGE_VERSION:-latest}
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.services.${DOMAIN:-localhost}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false

        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        gitlab_rails['gitlab_shell_ssh_port'] = 22

        registry_external_url 'https://registry.gitlab.services.${DOMAIN:-localhost}'
        registry_nginx['listen_port'] = 5100
        registry_nginx['listen_https'] = false

        registry_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        pages_external_url 'https://pages.gitlab.services.${DOMAIN:-localhost}'
        pages_nginx['listen_port'] = 5200
        pages_nginx['listen_https'] = false

        pages_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        gitlab_pages['inplace_chroot'] = true
        gitlab_pages['external_http'] = ['gitlab:5201']
    volumes:
      - ./services/gitlab/config:/etc/gitlab
      - ./services/gitlab/log:/var/log/gitlab
      - ./services/gitlab/data:/var/opt/gitlab
    ports:
      # Feel free to map this to a different port if that one is in use already
      - "22:22"
    labels:
      - traefik.enable=true
      # Host settings for GitLab itself
      - traefik.gitlab.frontend.rule=Host(`gitlab.services.${DOMAIN:-localhost}`)
      - traefik.gitlab.port=80
      # Host settings for the registry
      - traefik.registry.frontend.rule=Host(`registry.gitlab.services.${DOMAIN:-localhost}`)
      - traefik.registry.port=5100
      # Host settings for GitLab pages. Since I don't have a wildcard certificate, I list every domain on it's own here
      - traefik.pages.frontend.rule=Host(`pages.gitlab.services.${DOMAIN:-localhost}`, `${ORGANISATION}.pages.gitlab.services.${DOMAIN:-localhost}`)
      - traefik.pages.port=5201

networks:
  proxy:
    external: true
