version: "3"

secrets:
  REDIS_PASSWORD:
    file: ./services/redis/secrets/REDIS_PASSWORD

services:
  redis_cache:
    image: redis:${REDIS_IMAGE_VERSION:-latest}
    container_name: redis_cache
    volumes:
      - ./services/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - cache

networks:
  cache:
    external: true
